SELECT *
FROM v_takes

CREATE OR REPLACE VIEW v_takes as
SELECT stu_id, class_id
FROM TAKES;


SELECT TITLE
FROM COURSE c 
WHERE COURSE_ID  NOT IN 
(SELECT DISTINCT COURSE_ID
FROM CLASS c 
WHERE YEAR = 2012 AND SEMESTER = 2)


SELECT DISTINCT TITLE
FROM COURSE C1, CLASS c2
WHERE C1.COURSE_ID =C2.COURSE_ID AND CLASSROOM = '301호'


SELECT TITLE
FROM COURSE
WHERE COURSE_ID IN(
SELECT DISTINCT COURSE_ID
FROM CLASS c 
WHERE CLASSROOM ='301호'
)

SELECT *
FROM CLASS 
WHERE CLASSROOM='301호'


SELECT COUNT(COMM) 
FROM EMP e 
WHERE COMM IS NULL

SELECT *
FROM EMP e 
WHERE COMM=1400
--NULL값은 필드에서 다 자동으로 빠짐
SELECT *
FROM EMP e 
WHERE COMM<>1400

SELECT STU_ID
FROM TAKES t 
WHERE GRADE <>'A+'

SELECT STU_ID
FROM TAKES t
WHERE GRADE !='A+'


SELECT *
FROM EMP e 
WHERE COMM IS NOT NULL 


SELECT *
FROM EMP e 
WHERE COMM IS NULL 


SELECT DNAME,COUNT(*),AVG(SAL),MAX(SAL),MIN(SAL)
FROM EMP e ,DEPT d 
WHERE E.DEPTNO = D.DEPTNO
GROUP BY DNAME
HAVING COUNT(*) >=5 


SELECT DEPT_NAME,COUNT(*),AVG(2012-YEAR_EMP),MAX(2012-YEAR_EMP)
FROM PROFESSOR P,DEPARTMENT d 
WHERE P.DEPT_ID = D.DEPT_ID --AND AVG(2012-YEAR_EMP)>=10
GROUP BY DEPT_NAME
HAVING AVG(2012 - YEAR_EMP)>=10



SELECT DEPT_NAME,COUNT(*), AVG(2012-YEAR_EMP)평균 ,MAX(2012-YEAR_EMP)최대
FROM PROFESSOR P,DEPARTMENT D
WHERE P.DEPT_ID = D.DEPT_ID 
GROUP BY DEPT_NAME

select 	dname, count(*), avg(sal), max(sal), min(sal)
from 	emp e, dept d
where 	e.deptno = d.deptno
group by 	dname
ORDER BY DNAME


select 		dept_name, count(*)
from 		student s, department d
where 		s.dept_id = d.dept_id
group by 	dept_name



SELECT DEPT_NAME,COUNT(*)
FROM STUDENT s ,DEPARTMENT d 
WHERE S.DEPT_ID =D.DEPT_ID 
GROUP BY DEPT_NAME


SELECT DEPT_ID, COUNT(*)
FROM STUDENT s 
GROUP BY DEPT_ID



SELECT MAX(SAL), AVG(SAL), MIN(SAL),COUNT(SAL) 
FROM EMP E,DEPT D
WHERE E.DEPTNO = D.DEPTNO 
AND DNAME = 'ACCOUNTING'

SELECT AVG(SAL)
FROM EMP
WHERE JOB = 'CLERK'



SELECT AVG(2012-YEAR_EMP)
FROM PROFESSOR p 

AVG(2012-YEAR_EMP)

SELECT SUM(SAL)
FROM DEPT, EMP
WHERE DEPT.DEPTNO = EMP.DEPTNO
AND DNAME='RESEARCH'

SELECT * -- COUNT(MGR)
FROM EMP

SELECT * --COUNT(*)
FROM  STUDENT
WHERE YEAR =3

SELECT COUNT(DISTINCT DEPT_ID) 
FROM STUDENT

SELECT COUNT(*)
FROM STUDENT S, DEPARTMENT d
WHERE S.DEPT_ID = D.DEPT_ID 
AND D.DEPT_NAME = '컴퓨터공학과';

SELECT * FROM EMP

SELECT NAME, YEAR_EMP, 2012-YEAR_EMP
FROM PROFESSOR

SELECT SUM(2012-YEAR_EMP)
FROM PROFESSOR

SELECT COUNT(*)
FROM EMP
WHERE JOB='SALESMAN'
AND SAL>='1500'

SELECT SUM(SAL)
FROM EMP
WHERE JOB='SALESMAN'

SELECT *
FROM EMP

SELECT *
FROM DEPT d 
